### ISSUE TITLE
Afterlife OG hero pack?

### ISSUE THREAD

**Issue by jonogunn** [mr-kiou/q-pack#10]
Hi I was wondering if you can create a version of the sync generator that is based off the hero packs the OG’s wore in Afterlife? Basically it’s the same screw hole placements and the hole sizes for the blue/red cable/strain relief inserts as the afterlife version. 

Thanks just wanted to try and put it out there if possible. Appreciate you and your great work!

**Comment by TheTacoBelli** [comment]
It already existed at the time of this request.
