### ISSUE TITLE
Step Files

### ISSUE THREAD

**Issue by falo2k** [mr-kiou/q-pack#18]
Is there any chance of getting step files published for the pack (or even for older versions - selfishly running a 3.1 as my main build)?  I spend a lot of time messing around with internal layouts in CAD, designing mounts for electronics, etc. to check for clearances and converted meshes are beasting my PC when I want to navigate!  Understand if you're reluctant to do so.

**Comment by TheTacoBelli** [comment]
Not anymore due to etsy theft.

**Comment by falo2k** [comment]
Fair.  What a bunch of bastards (the people who can't respect licenses).
