### ISSUE TITLE
hole size/no recessed nuts on bracket_01.stl

### ISSUE THREAD

**Issue by uurf** [mr-kiou/q-pack#8]
I notice that the hole diameter for the upper two shell attachment bolts is smaller on [bracket_01-stl](https://github.com/mr-kiou/q-pack/blob/MK3/SHELL/MOTHER_BOARD/bracket_01.stl) than the other 3 brackets (m6), and lacks the recessed area to epoxy a nut to. Is this intentional?

bracket_01.stl
<img width="239" alt="image" src="https://user-images.githubusercontent.com/3910807/137038334-b6728ef2-74f8-4a56-b0a5-b9589b4f396d.png">

bracket_02.stl
<img width="326" alt="image" src="https://user-images.githubusercontent.com/3910807/137038396-dacddb13-ec74-44d8-93fe-704d3717460d.png">

bracket_03.stl
<img width="263" alt="image" src="https://user-images.githubusercontent.com/3910807/137038429-82fe58c5-3d79-4da2-baef-ad8a30576624.png">

**Comment by mr-kiou** [comment]
yes, it's made to fit two M3 on that side. screws was smaller on that side in the references used. anyway it can be edited if needed :)

**Comment by uurf** [comment]
closing "as intended"
